<script lang="ts">
  import type { Snippet } from "svelte";
  let { screen, keyboard, open = true, desktop = true, motion = true, paused = false, class: className = "" }: { screen: Snippet; keyboard?: Snippet; open?: boolean; desktop?: boolean; motion?: boolean; paused?: boolean; class?: string; } = $props();
</script>
<div class={`laptop-device ${className}`} class:open class:desktop class:motion class:paused>
  <div class="lid"><div class="lid-shell"><div class="lid-bezel"><div class="mac-screen">{@render screen()}<div class="camera-housing"></div></div></div></div></div>
  <div class="base-slot"><div class="base-clip"><div class="base"><div class="speaker speaker-left"></div><div class="keyboard-well">{#if keyboard}{@render keyboard()}{/if}</div><div class="speaker speaker-right"></div><div class="trackpad"></div></div></div></div>
</div>
<style>
  .laptop-device { --laptop-pivot: 0.5; position: relative; width: 100%; aspect-ratio: var(--macbook-deck-aspect); transform-style: flat; pointer-events: none; }
  .paused,.paused * { animation-play-state: paused !important; }
  .base-slot { position: absolute; z-index: 0; inset: 0; transform: perspective(var(--scene-perspective)) rotateX(var(--laptop-base-pitch)); transform-origin: 50% calc(100% * var(--laptop-pivot)); transform-style: preserve-3d; pointer-events: none; } .base-slot::before { position: absolute; z-index: 0; inset: 0; border-radius: var(--radius-laptop-base); box-shadow: var(--shadow-device); content: ""; }
  .base-clip { position: absolute; z-index: 2; inset: 0; overflow: hidden; border-radius: var(--radius-laptop-base); } .base-clip::before { position: absolute; inset: 0 calc(-1 * var(--base-edge-size)) var(--base-edge-size); border-radius: var(--radius-laptop-base); background: var(--studio-base-gradient); content: ""; transform: translateY(var(--base-edge-size)) skewX(-4deg); transform-origin: center; }
  .base { position: absolute; z-index: 0; inset: 0 0 var(--base-edge-size); display: grid; grid-template-columns: var(--speaker-width) 1fr var(--speaker-width); grid-template-rows: var(--keyboard-row-height) 1fr; gap: var(--deck-gap); padding: var(--deck-padding); border-radius: var(--radius-laptop-base); background: var(--device-shell-gradient); box-shadow: inset 0 var(--stroke-hairline) 0 var(--color-device-rim); transform-style: preserve-3d; }
  /* Compose the deck projection and hinge rotation on one flat plane so WebKit can scroll its contents. */
  .lid { --lid-angle: -180deg; --lid-pivot-offset: calc(100% * var(--laptop-pivot) / var(--macbook-lid-ratio)); position: absolute; z-index: 1; inset: auto 0 100%; height: var(--macbook-lid-height); transform: translateY(var(--lid-pivot-offset)) perspective(var(--scene-perspective)) rotateX(var(--laptop-base-pitch)) translateY(calc(-1 * var(--lid-pivot-offset))) rotateX(var(--lid-angle)); transform-origin: 50% 100%; transform-style: flat; } .motion .lid { transition: transform var(--motion-lid) var(--easing-mechanical); } .open .lid { --lid-angle: calc(-1 * var(--laptop-lid-open)); }
  .lid-shell { position: absolute; inset: 0; padding: var(--stroke-strong); border: var(--stroke-hairline) solid var(--color-line-strong); border-radius: var(--radius-laptop-lid); background: var(--device-shell-gradient); box-shadow: inset 0 0 0 var(--stroke-hairline) var(--color-device-rim), inset 0 var(--stroke-hairline) var(--space-1) var(--color-device-highlight); transform-style: preserve-3d; }
  .lid-bezel { position: relative; width: 100%; height: 100%; overflow: hidden; padding: var(--macbook-bezel-top) var(--macbook-bezel-inline) var(--macbook-bezel-bottom); border-radius: calc(var(--radius-laptop-lid) - var(--stroke-strong)); background: var(--color-display-bezel); box-shadow: inset 0 0 var(--space-1) color-mix(in srgb, var(--color-display-bezel-shadow) 38%, transparent); } .lid-bezel::after { position: absolute; z-index: 1; inset: auto var(--stroke-strong) var(--stroke-strong); height: calc(var(--macbook-bezel-bottom) - var(--stroke-strong)); border-radius: 0 0 calc(var(--radius-laptop-lid) - var(--stroke-strong)) calc(var(--radius-laptop-lid) - var(--stroke-strong)); background: linear-gradient(to bottom, color-mix(in srgb, var(--color-display-bezel-raised) 68%, var(--color-display-bezel)), var(--color-display-bezel)); content: ""; pointer-events: none; }
  .mac-screen { position: relative; width: 100%; height: 100%; overflow: hidden; border-radius: var(--radius-laptop-screen) var(--radius-laptop-screen) 0 0; background: var(--color-screen-background); backface-visibility: hidden; pointer-events: auto; --radius-screen-window: var(--radius-laptop-screen); }
  :global(.laptop-device:not(.desktop) .display-surface),:global(.laptop-device:not(.desktop) .screen-dock) { opacity: 0; pointer-events: none; }
  .camera-housing { position: absolute; z-index: var(--layer-controls); inset: 0 auto auto 50%; width: var(--camera-width); height: var(--camera-height); border-radius: 0 0 var(--radius-small) var(--radius-small); background: var(--color-display-bezel); transform: translateX(-50%); }
  .camera-housing::before,.camera-housing::after { position: absolute; inset-block-start: 0; width: var(--camera-join-size); aspect-ratio: 1; content: ""; } .camera-housing::before { inset-inline-start: calc(-1 * var(--camera-join-size)); background: radial-gradient(circle at bottom left, transparent 0 72%, var(--color-display-bezel) 74%); } .camera-housing::after { inset-inline-end: calc(-1 * var(--camera-join-size)); background: radial-gradient(circle at bottom right, transparent 0 72%, var(--color-display-bezel) 74%); }
  .keyboard-well { position: relative; grid-column: 2; min-width: 0; padding: var(--keyboard-well-padding); border: var(--stroke-hairline) solid var(--color-line-default); border-radius: var(--radius-small); background: color-mix(in srgb, var(--color-page-background) 52%, var(--color-device-shell)); box-shadow: inset 0 var(--keyboard-well-depth) var(--keyboard-well-shadow) color-mix(in srgb, var(--color-page-background) 64%, transparent), 0 var(--stroke-hairline) 0 var(--color-device-highlight); transform: translateZ(var(--deck-content-depth)); }
  .speaker { border-radius: var(--radius-small); background: var(--speaker-pattern); opacity: var(--opacity-64); } .speaker-left { grid-column: 1; } .speaker-right { grid-column: 3; } .trackpad { grid-column: 2; justify-self: center; width: var(--trackpad-width); border: var(--stroke-hairline) solid var(--color-line-default); border-radius: var(--radius-small); box-shadow: inset 0 var(--stroke-hairline) 0 var(--color-device-rim); }
  @media (prefers-reduced-motion: reduce) { .lid { transition-duration: var(--motion-reduced) !important; } }
</style>
