import { execFileSync } from "node:child_process";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createHeroSimulation } from "../src/lib/hero/create-hero-simulation.js";
import { fastForwardHeroSimulation, normalizeHeroSnapshot } from "../src/lib/hero/hero-snapshot.js";

const outputPath = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../src/lib/hero/generated-hero-snapshot.ts",
);

const renderModule = (snapshot: ReturnType<typeof normalizeHeroSnapshot>): string =>
  `// Generated by scripts/generate-hero-snapshot.ts. Do not edit.\n` +
  `import type { HeroFallbackSnapshot } from "./hero-snapshot.js";\n\n` +
  `export const generatedHeroSnapshot = ${JSON.stringify(snapshot, null, 2)} as const satisfies HeroFallbackSnapshot;\n`;

const formatModule = (source: string): string =>
  execFileSync("oxfmt", ["--stdin-filepath", outputPath], {
    encoding: "utf8",
    input: source,
  });

async function generate(): Promise<void> {
  const simulation = await createHeroSimulation();
  try {
    const snapshot = normalizeHeroSnapshot(await fastForwardHeroSimulation(simulation));
    const output = formatModule(renderModule(snapshot));
    const current = await readFile(outputPath, "utf8").catch(() => null);
    if (current === output) return;

    await mkdir(dirname(outputPath), { recursive: true });
    const temporaryPath = `${outputPath}.${process.pid}.tmp`;
    try {
      await writeFile(temporaryPath, output, { encoding: "utf8", flag: "wx" });
      await rename(temporaryPath, outputPath);
    } finally {
      await rm(temporaryPath, { force: true });
    }
  } finally {
    await simulation.dispose();
  }
}

await generate();
